cameras:
  - camera_id: "entry_01"
    name: "Entry Camera"
    url: "rtsp://admin:Vinil@123@192.168.0.150:554/h264/ch1/main/av_stream"
    enabled: ture
    location: "Main Entrance"
    event_type: "login"

  - camera_id: "webcam_01"
    url: 0 # Webcam
    event_type: "login"
    enabled: false

  - camera_id: "exit_01"
    name: "Exit Camera"
    url: "rtsp://admin:Vinil@123@192.168.0.150:554/h264/ch1/main/av_stream"
    enabled: false
    location: "Main Exit"
    event_type: "logout"

  - camera_id: "exit_02"
    url: "rtsp://192.168.0.102:8080/h264_pcm.sdp"
    event_type: "logout"
    enabled: false

  # Add more cameras as needed
  # - camera_id: "exit_01"
  #   url: "rtsp://admin:password@192.168.0.151:554/h264/ch1/main/av_stream"
  #   event_type: "logout"
  #   enabled: false

# Recognition settings
recognition:
  confidence_threshold: 0.40
  detection_confidence: 0.6
  logging_interval: 500 # seconds
  frame_skip: 2

# Performance settings
performance:
  max_resolution_width: 1280
  batch_size: 4
  recognition_interval: 0.1

  # ===========================================
#   # For HIGH FREQUENCY logging (every 10 seconds)
# recognition:
#   confidence_threshold: 0.35
#   logging_interval: 10
#   frame_skip: 1
# performance:
#   recognition_interval: 0.05

# # For LOW FREQUENCY logging (every 5 minutes)
# recognition:
#   confidence_threshold: 0.60
#   logging_interval: 300
#   frame_skip: 3
# performance:
#   recognition_interval: 0.2

# # For BALANCED logging (current setup is good)
# recognition:
#   confidence_threshold: 0.40
#   logging_interval: 30
#   frame_skip: 2
# performance:
#   recognition_interval: 0.1