[application]
name = "CCTV Attendance Monitor"
version = "1.0.0"

[database]
host = "localhost"
port = 5432
name = "attendance_db"
user = "postgres"
password = ""

[paths]
config = "./config"
snapshots = "./snapshots"